package com.yanglin.model;

import java.util.Date;

public class HistorycaseInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.peianhao
     *
     * @mbggenerated
     */
    private String peianhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.baodanhao
     *
     * @mbggenerated
     */
    private String baodanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.baoanren
     *
     * @mbggenerated
     */
    private String baoanren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.baoan_dianhua
     *
     * @mbggenerated
     */
    private String baoanDianhua;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.boan_shijian
     *
     * @mbggenerated
     */
    private Date boanShijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.jiashiyuan
     *
     * @mbggenerated
     */
    private String jiashiyuan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.chepaihao
     *
     * @mbggenerated
     */
    private String chepaihao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.chuxian_shijian
     *
     * @mbggenerated
     */
    private Date chuxianShijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.chuxian_yuanyin
     *
     * @mbggenerated
     */
    private String chuxianYuanyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.jieanzhuangtai
     *
     * @mbggenerated
     */
    private String jieanzhuangtai;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.peifu_shijian
     *
     * @mbggenerated
     */
    private Date peifuShijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.peifu_xianzhongmingcheng
     *
     * @mbggenerated
     */
    private String peifuXianzhongmingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.shifou_yousanzheche
     *
     * @mbggenerated
     */
    private String shifouYousanzheche;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.sanzheche_chelianghao
     *
     * @mbggenerated
     */
    private String sanzhecheChelianghao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.sanzheche_vin
     *
     * @mbggenerated
     */
    private String sanzhecheVin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.sanzheche_chexing
     *
     * @mbggenerated
     */
    private String sanzhecheChexing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.xiulichang_mingcheng
     *
     * @mbggenerated
     */
    private String xiulichangMingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historycaseinfo.xiulichang_leixing
     *
     * @mbggenerated
     */
    private String xiulichangLeixing;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.peianhao
     *
     * @return the value of historycaseinfo.peianhao
     *
     * @mbggenerated
     */
    public String getPeianhao() {
        return peianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.peianhao
     *
     * @param peianhao the value for historycaseinfo.peianhao
     *
     * @mbggenerated
     */
    public void setPeianhao(String peianhao) {
        this.peianhao = peianhao == null ? null : peianhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.baodanhao
     *
     * @return the value of historycaseinfo.baodanhao
     *
     * @mbggenerated
     */
    public String getBaodanhao() {
        return baodanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.baodanhao
     *
     * @param baodanhao the value for historycaseinfo.baodanhao
     *
     * @mbggenerated
     */
    public void setBaodanhao(String baodanhao) {
        this.baodanhao = baodanhao == null ? null : baodanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.baoanren
     *
     * @return the value of historycaseinfo.baoanren
     *
     * @mbggenerated
     */
    public String getBaoanren() {
        return baoanren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.baoanren
     *
     * @param baoanren the value for historycaseinfo.baoanren
     *
     * @mbggenerated
     */
    public void setBaoanren(String baoanren) {
        this.baoanren = baoanren == null ? null : baoanren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.baoan_dianhua
     *
     * @return the value of historycaseinfo.baoan_dianhua
     *
     * @mbggenerated
     */
    public String getBaoanDianhua() {
        return baoanDianhua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.baoan_dianhua
     *
     * @param baoanDianhua the value for historycaseinfo.baoan_dianhua
     *
     * @mbggenerated
     */
    public void setBaoanDianhua(String baoanDianhua) {
        this.baoanDianhua = baoanDianhua == null ? null : baoanDianhua.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.boan_shijian
     *
     * @return the value of historycaseinfo.boan_shijian
     *
     * @mbggenerated
     */
    public Date getBoanShijian() {
        return boanShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.boan_shijian
     *
     * @param boanShijian the value for historycaseinfo.boan_shijian
     *
     * @mbggenerated
     */
    public void setBoanShijian(Date boanShijian) {
        this.boanShijian = boanShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.jiashiyuan
     *
     * @return the value of historycaseinfo.jiashiyuan
     *
     * @mbggenerated
     */
    public String getJiashiyuan() {
        return jiashiyuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.jiashiyuan
     *
     * @param jiashiyuan the value for historycaseinfo.jiashiyuan
     *
     * @mbggenerated
     */
    public void setJiashiyuan(String jiashiyuan) {
        this.jiashiyuan = jiashiyuan == null ? null : jiashiyuan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.chepaihao
     *
     * @return the value of historycaseinfo.chepaihao
     *
     * @mbggenerated
     */
    public String getChepaihao() {
        return chepaihao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.chepaihao
     *
     * @param chepaihao the value for historycaseinfo.chepaihao
     *
     * @mbggenerated
     */
    public void setChepaihao(String chepaihao) {
        this.chepaihao = chepaihao == null ? null : chepaihao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.chuxian_shijian
     *
     * @return the value of historycaseinfo.chuxian_shijian
     *
     * @mbggenerated
     */
    public Date getChuxianShijian() {
        return chuxianShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.chuxian_shijian
     *
     * @param chuxianShijian the value for historycaseinfo.chuxian_shijian
     *
     * @mbggenerated
     */
    public void setChuxianShijian(Date chuxianShijian) {
        this.chuxianShijian = chuxianShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.chuxian_yuanyin
     *
     * @return the value of historycaseinfo.chuxian_yuanyin
     *
     * @mbggenerated
     */
    public String getChuxianYuanyin() {
        return chuxianYuanyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.chuxian_yuanyin
     *
     * @param chuxianYuanyin the value for historycaseinfo.chuxian_yuanyin
     *
     * @mbggenerated
     */
    public void setChuxianYuanyin(String chuxianYuanyin) {
        this.chuxianYuanyin = chuxianYuanyin == null ? null : chuxianYuanyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.jieanzhuangtai
     *
     * @return the value of historycaseinfo.jieanzhuangtai
     *
     * @mbggenerated
     */
    public String getJieanzhuangtai() {
        return jieanzhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.jieanzhuangtai
     *
     * @param jieanzhuangtai the value for historycaseinfo.jieanzhuangtai
     *
     * @mbggenerated
     */
    public void setJieanzhuangtai(String jieanzhuangtai) {
        this.jieanzhuangtai = jieanzhuangtai == null ? null : jieanzhuangtai.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.peifu_shijian
     *
     * @return the value of historycaseinfo.peifu_shijian
     *
     * @mbggenerated
     */
    public Date getPeifuShijian() {
        return peifuShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.peifu_shijian
     *
     * @param peifuShijian the value for historycaseinfo.peifu_shijian
     *
     * @mbggenerated
     */
    public void setPeifuShijian(Date peifuShijian) {
        this.peifuShijian = peifuShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.peifu_xianzhongmingcheng
     *
     * @return the value of historycaseinfo.peifu_xianzhongmingcheng
     *
     * @mbggenerated
     */
    public String getPeifuXianzhongmingcheng() {
        return peifuXianzhongmingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.peifu_xianzhongmingcheng
     *
     * @param peifuXianzhongmingcheng the value for historycaseinfo.peifu_xianzhongmingcheng
     *
     * @mbggenerated
     */
    public void setPeifuXianzhongmingcheng(String peifuXianzhongmingcheng) {
        this.peifuXianzhongmingcheng = peifuXianzhongmingcheng == null ? null : peifuXianzhongmingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.shifou_yousanzheche
     *
     * @return the value of historycaseinfo.shifou_yousanzheche
     *
     * @mbggenerated
     */
    public String getShifouYousanzheche() {
        return shifouYousanzheche;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.shifou_yousanzheche
     *
     * @param shifouYousanzheche the value for historycaseinfo.shifou_yousanzheche
     *
     * @mbggenerated
     */
    public void setShifouYousanzheche(String shifouYousanzheche) {
        this.shifouYousanzheche = shifouYousanzheche == null ? null : shifouYousanzheche.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.sanzheche_chelianghao
     *
     * @return the value of historycaseinfo.sanzheche_chelianghao
     *
     * @mbggenerated
     */
    public String getSanzhecheChelianghao() {
        return sanzhecheChelianghao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.sanzheche_chelianghao
     *
     * @param sanzhecheChelianghao the value for historycaseinfo.sanzheche_chelianghao
     *
     * @mbggenerated
     */
    public void setSanzhecheChelianghao(String sanzhecheChelianghao) {
        this.sanzhecheChelianghao = sanzhecheChelianghao == null ? null : sanzhecheChelianghao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.sanzheche_vin
     *
     * @return the value of historycaseinfo.sanzheche_vin
     *
     * @mbggenerated
     */
    public String getSanzhecheVin() {
        return sanzhecheVin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.sanzheche_vin
     *
     * @param sanzhecheVin the value for historycaseinfo.sanzheche_vin
     *
     * @mbggenerated
     */
    public void setSanzhecheVin(String sanzhecheVin) {
        this.sanzhecheVin = sanzhecheVin == null ? null : sanzhecheVin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.sanzheche_chexing
     *
     * @return the value of historycaseinfo.sanzheche_chexing
     *
     * @mbggenerated
     */
    public String getSanzhecheChexing() {
        return sanzhecheChexing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.sanzheche_chexing
     *
     * @param sanzhecheChexing the value for historycaseinfo.sanzheche_chexing
     *
     * @mbggenerated
     */
    public void setSanzhecheChexing(String sanzhecheChexing) {
        this.sanzhecheChexing = sanzhecheChexing == null ? null : sanzhecheChexing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.xiulichang_mingcheng
     *
     * @return the value of historycaseinfo.xiulichang_mingcheng
     *
     * @mbggenerated
     */
    public String getXiulichangMingcheng() {
        return xiulichangMingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.xiulichang_mingcheng
     *
     * @param xiulichangMingcheng the value for historycaseinfo.xiulichang_mingcheng
     *
     * @mbggenerated
     */
    public void setXiulichangMingcheng(String xiulichangMingcheng) {
        this.xiulichangMingcheng = xiulichangMingcheng == null ? null : xiulichangMingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historycaseinfo.xiulichang_leixing
     *
     * @return the value of historycaseinfo.xiulichang_leixing
     *
     * @mbggenerated
     */
    public String getXiulichangLeixing() {
        return xiulichangLeixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historycaseinfo.xiulichang_leixing
     *
     * @param xiulichangLeixing the value for historycaseinfo.xiulichang_leixing
     *
     * @mbggenerated
     */
    public void setXiulichangLeixing(String xiulichangLeixing) {
        this.xiulichangLeixing = xiulichangLeixing == null ? null : xiulichangLeixing.trim();
    }
}