package com.yanglin.model;

import java.util.Date;

public class LossaccessmentOpinions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_opinions.baoanhao
     *
     * @mbggenerated
     */
    private String baoanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_opinions.chepaihao
     *
     * @mbggenerated
     */
    private String chepaihao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_opinions.hesunren
     *
     * @mbggenerated
     */
    private String hesunren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_opinions.juese
     *
     * @mbggenerated
     */
    private String juese;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_opinions.caozuo_shijian
     *
     * @mbggenerated
     */
    private Date caozuoShijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_opinions.yijian_mingcheng
     *
     * @mbggenerated
     */
    private String yijianMingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_opinions.yijian_shuoming
     *
     * @mbggenerated
     */
    private String yijianShuoming;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_opinions.baoanhao
     *
     * @return the value of lossaccessment_opinions.baoanhao
     *
     * @mbggenerated
     */
    public String getBaoanhao() {
        return baoanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_opinions.baoanhao
     *
     * @param baoanhao the value for lossaccessment_opinions.baoanhao
     *
     * @mbggenerated
     */
    public void setBaoanhao(String baoanhao) {
        this.baoanhao = baoanhao == null ? null : baoanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_opinions.chepaihao
     *
     * @return the value of lossaccessment_opinions.chepaihao
     *
     * @mbggenerated
     */
    public String getChepaihao() {
        return chepaihao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_opinions.chepaihao
     *
     * @param chepaihao the value for lossaccessment_opinions.chepaihao
     *
     * @mbggenerated
     */
    public void setChepaihao(String chepaihao) {
        this.chepaihao = chepaihao == null ? null : chepaihao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_opinions.hesunren
     *
     * @return the value of lossaccessment_opinions.hesunren
     *
     * @mbggenerated
     */
    public String getHesunren() {
        return hesunren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_opinions.hesunren
     *
     * @param hesunren the value for lossaccessment_opinions.hesunren
     *
     * @mbggenerated
     */
    public void setHesunren(String hesunren) {
        this.hesunren = hesunren == null ? null : hesunren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_opinions.juese
     *
     * @return the value of lossaccessment_opinions.juese
     *
     * @mbggenerated
     */
    public String getJuese() {
        return juese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_opinions.juese
     *
     * @param juese the value for lossaccessment_opinions.juese
     *
     * @mbggenerated
     */
    public void setJuese(String juese) {
        this.juese = juese == null ? null : juese.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_opinions.caozuo_shijian
     *
     * @return the value of lossaccessment_opinions.caozuo_shijian
     *
     * @mbggenerated
     */
    public Date getCaozuoShijian() {
        return caozuoShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_opinions.caozuo_shijian
     *
     * @param caozuoShijian the value for lossaccessment_opinions.caozuo_shijian
     *
     * @mbggenerated
     */
    public void setCaozuoShijian(Date caozuoShijian) {
        this.caozuoShijian = caozuoShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_opinions.yijian_mingcheng
     *
     * @return the value of lossaccessment_opinions.yijian_mingcheng
     *
     * @mbggenerated
     */
    public String getYijianMingcheng() {
        return yijianMingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_opinions.yijian_mingcheng
     *
     * @param yijianMingcheng the value for lossaccessment_opinions.yijian_mingcheng
     *
     * @mbggenerated
     */
    public void setYijianMingcheng(String yijianMingcheng) {
        this.yijianMingcheng = yijianMingcheng == null ? null : yijianMingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_opinions.yijian_shuoming
     *
     * @return the value of lossaccessment_opinions.yijian_shuoming
     *
     * @mbggenerated
     */
    public String getYijianShuoming() {
        return yijianShuoming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_opinions.yijian_shuoming
     *
     * @param yijianShuoming the value for lossaccessment_opinions.yijian_shuoming
     *
     * @mbggenerated
     */
    public void setYijianShuoming(String yijianShuoming) {
        this.yijianShuoming = yijianShuoming == null ? null : yijianShuoming.trim();
    }
}