package com.yanglin.model;

import java.math.BigDecimal;
import java.util.Date;

public class LossaccessmentVehicle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_vehicle.baoanhao
     *
     * @mbggenerated
     */
    private String baoanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_vehicle.shifou_biaodiche
     *
     * @mbggenerated
     */
    private String shifouBiaodiche;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_vehicle.chepaihao
     *
     * @mbggenerated
     */
    private String chepaihao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_vehicle.VIN
     *
     * @mbggenerated
     */
    private String vin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_vehicle.dingsun_chexing
     *
     * @mbggenerated
     */
    private String dingsunChexing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_vehicle.zuoweishu
     *
     * @mbggenerated
     */
    private String zuoweishu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_vehicle.cheliang_zhonglei
     *
     * @mbggenerated
     */
    private String cheliangZhonglei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_vehicle.shiyongxingzhi
     *
     * @mbggenerated
     */
    private String shiyongxingzhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_vehicle.ranliao_leixing
     *
     * @mbggenerated
     */
    private String ranliaoLeixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_vehicle.peiliang
     *
     * @mbggenerated
     */
    private BigDecimal peiliang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_vehicle.biansuxiang_leixing
     *
     * @mbggenerated
     */
    private String biansuxiangLeixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_vehicle.xingshi_lichengshu
     *
     * @mbggenerated
     */
    private Long xingshiLichengshu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_vehicle.shengchan_nianfen
     *
     * @mbggenerated
     */
    private Date shengchanNianfen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_vehicle.shiyong_nianxian
     *
     * @mbggenerated
     */
    private Integer shiyongNianxian;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_vehicle.baoanhao
     *
     * @return the value of lossaccessment_vehicle.baoanhao
     *
     * @mbggenerated
     */
    public String getBaoanhao() {
        return baoanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_vehicle.baoanhao
     *
     * @param baoanhao the value for lossaccessment_vehicle.baoanhao
     *
     * @mbggenerated
     */
    public void setBaoanhao(String baoanhao) {
        this.baoanhao = baoanhao == null ? null : baoanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_vehicle.shifou_biaodiche
     *
     * @return the value of lossaccessment_vehicle.shifou_biaodiche
     *
     * @mbggenerated
     */
    public String getShifouBiaodiche() {
        return shifouBiaodiche;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_vehicle.shifou_biaodiche
     *
     * @param shifouBiaodiche the value for lossaccessment_vehicle.shifou_biaodiche
     *
     * @mbggenerated
     */
    public void setShifouBiaodiche(String shifouBiaodiche) {
        this.shifouBiaodiche = shifouBiaodiche == null ? null : shifouBiaodiche.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_vehicle.chepaihao
     *
     * @return the value of lossaccessment_vehicle.chepaihao
     *
     * @mbggenerated
     */
    public String getChepaihao() {
        return chepaihao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_vehicle.chepaihao
     *
     * @param chepaihao the value for lossaccessment_vehicle.chepaihao
     *
     * @mbggenerated
     */
    public void setChepaihao(String chepaihao) {
        this.chepaihao = chepaihao == null ? null : chepaihao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_vehicle.VIN
     *
     * @return the value of lossaccessment_vehicle.VIN
     *
     * @mbggenerated
     */
    public String getVin() {
        return vin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_vehicle.VIN
     *
     * @param vin the value for lossaccessment_vehicle.VIN
     *
     * @mbggenerated
     */
    public void setVin(String vin) {
        this.vin = vin == null ? null : vin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_vehicle.dingsun_chexing
     *
     * @return the value of lossaccessment_vehicle.dingsun_chexing
     *
     * @mbggenerated
     */
    public String getDingsunChexing() {
        return dingsunChexing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_vehicle.dingsun_chexing
     *
     * @param dingsunChexing the value for lossaccessment_vehicle.dingsun_chexing
     *
     * @mbggenerated
     */
    public void setDingsunChexing(String dingsunChexing) {
        this.dingsunChexing = dingsunChexing == null ? null : dingsunChexing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_vehicle.zuoweishu
     *
     * @return the value of lossaccessment_vehicle.zuoweishu
     *
     * @mbggenerated
     */
    public String getZuoweishu() {
        return zuoweishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_vehicle.zuoweishu
     *
     * @param zuoweishu the value for lossaccessment_vehicle.zuoweishu
     *
     * @mbggenerated
     */
    public void setZuoweishu(String zuoweishu) {
        this.zuoweishu = zuoweishu == null ? null : zuoweishu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_vehicle.cheliang_zhonglei
     *
     * @return the value of lossaccessment_vehicle.cheliang_zhonglei
     *
     * @mbggenerated
     */
    public String getCheliangZhonglei() {
        return cheliangZhonglei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_vehicle.cheliang_zhonglei
     *
     * @param cheliangZhonglei the value for lossaccessment_vehicle.cheliang_zhonglei
     *
     * @mbggenerated
     */
    public void setCheliangZhonglei(String cheliangZhonglei) {
        this.cheliangZhonglei = cheliangZhonglei == null ? null : cheliangZhonglei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_vehicle.shiyongxingzhi
     *
     * @return the value of lossaccessment_vehicle.shiyongxingzhi
     *
     * @mbggenerated
     */
    public String getShiyongxingzhi() {
        return shiyongxingzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_vehicle.shiyongxingzhi
     *
     * @param shiyongxingzhi the value for lossaccessment_vehicle.shiyongxingzhi
     *
     * @mbggenerated
     */
    public void setShiyongxingzhi(String shiyongxingzhi) {
        this.shiyongxingzhi = shiyongxingzhi == null ? null : shiyongxingzhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_vehicle.ranliao_leixing
     *
     * @return the value of lossaccessment_vehicle.ranliao_leixing
     *
     * @mbggenerated
     */
    public String getRanliaoLeixing() {
        return ranliaoLeixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_vehicle.ranliao_leixing
     *
     * @param ranliaoLeixing the value for lossaccessment_vehicle.ranliao_leixing
     *
     * @mbggenerated
     */
    public void setRanliaoLeixing(String ranliaoLeixing) {
        this.ranliaoLeixing = ranliaoLeixing == null ? null : ranliaoLeixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_vehicle.peiliang
     *
     * @return the value of lossaccessment_vehicle.peiliang
     *
     * @mbggenerated
     */
    public BigDecimal getPeiliang() {
        return peiliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_vehicle.peiliang
     *
     * @param peiliang the value for lossaccessment_vehicle.peiliang
     *
     * @mbggenerated
     */
    public void setPeiliang(BigDecimal peiliang) {
        this.peiliang = peiliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_vehicle.biansuxiang_leixing
     *
     * @return the value of lossaccessment_vehicle.biansuxiang_leixing
     *
     * @mbggenerated
     */
    public String getBiansuxiangLeixing() {
        return biansuxiangLeixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_vehicle.biansuxiang_leixing
     *
     * @param biansuxiangLeixing the value for lossaccessment_vehicle.biansuxiang_leixing
     *
     * @mbggenerated
     */
    public void setBiansuxiangLeixing(String biansuxiangLeixing) {
        this.biansuxiangLeixing = biansuxiangLeixing == null ? null : biansuxiangLeixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_vehicle.xingshi_lichengshu
     *
     * @return the value of lossaccessment_vehicle.xingshi_lichengshu
     *
     * @mbggenerated
     */
    public Long getXingshiLichengshu() {
        return xingshiLichengshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_vehicle.xingshi_lichengshu
     *
     * @param xingshiLichengshu the value for lossaccessment_vehicle.xingshi_lichengshu
     *
     * @mbggenerated
     */
    public void setXingshiLichengshu(Long xingshiLichengshu) {
        this.xingshiLichengshu = xingshiLichengshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_vehicle.shengchan_nianfen
     *
     * @return the value of lossaccessment_vehicle.shengchan_nianfen
     *
     * @mbggenerated
     */
    public Date getShengchanNianfen() {
        return shengchanNianfen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_vehicle.shengchan_nianfen
     *
     * @param shengchanNianfen the value for lossaccessment_vehicle.shengchan_nianfen
     *
     * @mbggenerated
     */
    public void setShengchanNianfen(Date shengchanNianfen) {
        this.shengchanNianfen = shengchanNianfen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_vehicle.shiyong_nianxian
     *
     * @return the value of lossaccessment_vehicle.shiyong_nianxian
     *
     * @mbggenerated
     */
    public Integer getShiyongNianxian() {
        return shiyongNianxian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_vehicle.shiyong_nianxian
     *
     * @param shiyongNianxian the value for lossaccessment_vehicle.shiyong_nianxian
     *
     * @mbggenerated
     */
    public void setShiyongNianxian(Integer shiyongNianxian) {
        this.shiyongNianxian = shiyongNianxian;
    }
}