package com.yanglin.model;

public class LossaccessmentCasualites {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_casualites.baoanhao
     *
     * @mbggenerated
     */
    private String baoanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_casualites.xingming
     *
     * @mbggenerated
     */
    private String xingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_casualites.xingbie
     *
     * @mbggenerated
     */
    private String xingbie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_casualites.shangwang_leibie
     *
     * @mbggenerated
     */
    private String shangwangLeibie;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_casualites.baoanhao
     *
     * @return the value of lossaccessment_casualites.baoanhao
     *
     * @mbggenerated
     */
    public String getBaoanhao() {
        return baoanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_casualites.baoanhao
     *
     * @param baoanhao the value for lossaccessment_casualites.baoanhao
     *
     * @mbggenerated
     */
    public void setBaoanhao(String baoanhao) {
        this.baoanhao = baoanhao == null ? null : baoanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_casualites.xingming
     *
     * @return the value of lossaccessment_casualites.xingming
     *
     * @mbggenerated
     */
    public String getXingming() {
        return xingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_casualites.xingming
     *
     * @param xingming the value for lossaccessment_casualites.xingming
     *
     * @mbggenerated
     */
    public void setXingming(String xingming) {
        this.xingming = xingming == null ? null : xingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_casualites.xingbie
     *
     * @return the value of lossaccessment_casualites.xingbie
     *
     * @mbggenerated
     */
    public String getXingbie() {
        return xingbie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_casualites.xingbie
     *
     * @param xingbie the value for lossaccessment_casualites.xingbie
     *
     * @mbggenerated
     */
    public void setXingbie(String xingbie) {
        this.xingbie = xingbie == null ? null : xingbie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_casualites.shangwang_leibie
     *
     * @return the value of lossaccessment_casualites.shangwang_leibie
     *
     * @mbggenerated
     */
    public String getShangwangLeibie() {
        return shangwangLeibie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_casualites.shangwang_leibie
     *
     * @param shangwangLeibie the value for lossaccessment_casualites.shangwang_leibie
     *
     * @mbggenerated
     */
    public void setShangwangLeibie(String shangwangLeibie) {
        this.shangwangLeibie = shangwangLeibie == null ? null : shangwangLeibie.trim();
    }
}