package com.yanglin.model;

import java.math.BigDecimal;

public class LossaccessmentLabors {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_labors.baoanhao
     *
     * @mbggenerated
     */
    private String baoanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_labors.chepaihao
     *
     * @mbggenerated
     */
    private String chepaihao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_labors.gongshi_mingcheng
     *
     * @mbggenerated
     */
    private String gongshiMingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_labors.gognshi_leixing
     *
     * @mbggenerated
     */
    private String gognshiLeixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_labors.shifou_shoudongshuru
     *
     * @mbggenerated
     */
    private String shifouShoudongshuru;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_labors.shifou_neixiu
     *
     * @mbggenerated
     */
    private String shifouNeixiu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_labors.beizhu
     *
     * @mbggenerated
     */
    private String beizhu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_labors.danjia
     *
     * @mbggenerated
     */
    private BigDecimal danjia;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_labors.baoanhao
     *
     * @return the value of lossaccessment_labors.baoanhao
     *
     * @mbggenerated
     */
    public String getBaoanhao() {
        return baoanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_labors.baoanhao
     *
     * @param baoanhao the value for lossaccessment_labors.baoanhao
     *
     * @mbggenerated
     */
    public void setBaoanhao(String baoanhao) {
        this.baoanhao = baoanhao == null ? null : baoanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_labors.chepaihao
     *
     * @return the value of lossaccessment_labors.chepaihao
     *
     * @mbggenerated
     */
    public String getChepaihao() {
        return chepaihao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_labors.chepaihao
     *
     * @param chepaihao the value for lossaccessment_labors.chepaihao
     *
     * @mbggenerated
     */
    public void setChepaihao(String chepaihao) {
        this.chepaihao = chepaihao == null ? null : chepaihao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_labors.gongshi_mingcheng
     *
     * @return the value of lossaccessment_labors.gongshi_mingcheng
     *
     * @mbggenerated
     */
    public String getGongshiMingcheng() {
        return gongshiMingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_labors.gongshi_mingcheng
     *
     * @param gongshiMingcheng the value for lossaccessment_labors.gongshi_mingcheng
     *
     * @mbggenerated
     */
    public void setGongshiMingcheng(String gongshiMingcheng) {
        this.gongshiMingcheng = gongshiMingcheng == null ? null : gongshiMingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_labors.gognshi_leixing
     *
     * @return the value of lossaccessment_labors.gognshi_leixing
     *
     * @mbggenerated
     */
    public String getGognshiLeixing() {
        return gognshiLeixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_labors.gognshi_leixing
     *
     * @param gognshiLeixing the value for lossaccessment_labors.gognshi_leixing
     *
     * @mbggenerated
     */
    public void setGognshiLeixing(String gognshiLeixing) {
        this.gognshiLeixing = gognshiLeixing == null ? null : gognshiLeixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_labors.shifou_shoudongshuru
     *
     * @return the value of lossaccessment_labors.shifou_shoudongshuru
     *
     * @mbggenerated
     */
    public String getShifouShoudongshuru() {
        return shifouShoudongshuru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_labors.shifou_shoudongshuru
     *
     * @param shifouShoudongshuru the value for lossaccessment_labors.shifou_shoudongshuru
     *
     * @mbggenerated
     */
    public void setShifouShoudongshuru(String shifouShoudongshuru) {
        this.shifouShoudongshuru = shifouShoudongshuru == null ? null : shifouShoudongshuru.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_labors.shifou_neixiu
     *
     * @return the value of lossaccessment_labors.shifou_neixiu
     *
     * @mbggenerated
     */
    public String getShifouNeixiu() {
        return shifouNeixiu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_labors.shifou_neixiu
     *
     * @param shifouNeixiu the value for lossaccessment_labors.shifou_neixiu
     *
     * @mbggenerated
     */
    public void setShifouNeixiu(String shifouNeixiu) {
        this.shifouNeixiu = shifouNeixiu == null ? null : shifouNeixiu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_labors.beizhu
     *
     * @return the value of lossaccessment_labors.beizhu
     *
     * @mbggenerated
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_labors.beizhu
     *
     * @param beizhu the value for lossaccessment_labors.beizhu
     *
     * @mbggenerated
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu == null ? null : beizhu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_labors.danjia
     *
     * @return the value of lossaccessment_labors.danjia
     *
     * @mbggenerated
     */
    public BigDecimal getDanjia() {
        return danjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_labors.danjia
     *
     * @param danjia the value for lossaccessment_labors.danjia
     *
     * @mbggenerated
     */
    public void setDanjia(BigDecimal danjia) {
        this.danjia = danjia;
    }
}