package com.yanglin.model;

import java.math.BigDecimal;

public class LossaccessmentSpareparts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_spareparts.baoanhao
     *
     * @mbggenerated
     */
    private String baoanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_spareparts.chepaihao
     *
     * @mbggenerated
     */
    private String chepaihao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_spareparts.peijianxiangmu_mingcheng
     *
     * @mbggenerated
     */
    private String peijianxiangmuMingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_spareparts.shifou_shoudongshuru
     *
     * @mbggenerated
     */
    private String shifouShoudongshuru;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_spareparts.OEM
     *
     * @mbggenerated
     */
    private String oem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_spareparts.shifou_neixiu
     *
     * @mbggenerated
     */
    private String shifouNeixiu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_spareparts.danjia
     *
     * @mbggenerated
     */
    private BigDecimal danjia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_spareparts.shuliang
     *
     * @mbggenerated
     */
    private Long shuliang;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_spareparts.xiaoji_jine
     *
     * @mbggenerated
     */
    private BigDecimal xiaojiJine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment_spareparts.beizhu
     *
     * @mbggenerated
     */
    private String beizhu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_spareparts.baoanhao
     *
     * @return the value of lossaccessment_spareparts.baoanhao
     *
     * @mbggenerated
     */
    public String getBaoanhao() {
        return baoanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_spareparts.baoanhao
     *
     * @param baoanhao the value for lossaccessment_spareparts.baoanhao
     *
     * @mbggenerated
     */
    public void setBaoanhao(String baoanhao) {
        this.baoanhao = baoanhao == null ? null : baoanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_spareparts.chepaihao
     *
     * @return the value of lossaccessment_spareparts.chepaihao
     *
     * @mbggenerated
     */
    public String getChepaihao() {
        return chepaihao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_spareparts.chepaihao
     *
     * @param chepaihao the value for lossaccessment_spareparts.chepaihao
     *
     * @mbggenerated
     */
    public void setChepaihao(String chepaihao) {
        this.chepaihao = chepaihao == null ? null : chepaihao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_spareparts.peijianxiangmu_mingcheng
     *
     * @return the value of lossaccessment_spareparts.peijianxiangmu_mingcheng
     *
     * @mbggenerated
     */
    public String getPeijianxiangmuMingcheng() {
        return peijianxiangmuMingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_spareparts.peijianxiangmu_mingcheng
     *
     * @param peijianxiangmuMingcheng the value for lossaccessment_spareparts.peijianxiangmu_mingcheng
     *
     * @mbggenerated
     */
    public void setPeijianxiangmuMingcheng(String peijianxiangmuMingcheng) {
        this.peijianxiangmuMingcheng = peijianxiangmuMingcheng == null ? null : peijianxiangmuMingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_spareparts.shifou_shoudongshuru
     *
     * @return the value of lossaccessment_spareparts.shifou_shoudongshuru
     *
     * @mbggenerated
     */
    public String getShifouShoudongshuru() {
        return shifouShoudongshuru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_spareparts.shifou_shoudongshuru
     *
     * @param shifouShoudongshuru the value for lossaccessment_spareparts.shifou_shoudongshuru
     *
     * @mbggenerated
     */
    public void setShifouShoudongshuru(String shifouShoudongshuru) {
        this.shifouShoudongshuru = shifouShoudongshuru == null ? null : shifouShoudongshuru.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_spareparts.OEM
     *
     * @return the value of lossaccessment_spareparts.OEM
     *
     * @mbggenerated
     */
    public String getOem() {
        return oem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_spareparts.OEM
     *
     * @param oem the value for lossaccessment_spareparts.OEM
     *
     * @mbggenerated
     */
    public void setOem(String oem) {
        this.oem = oem == null ? null : oem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_spareparts.shifou_neixiu
     *
     * @return the value of lossaccessment_spareparts.shifou_neixiu
     *
     * @mbggenerated
     */
    public String getShifouNeixiu() {
        return shifouNeixiu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_spareparts.shifou_neixiu
     *
     * @param shifouNeixiu the value for lossaccessment_spareparts.shifou_neixiu
     *
     * @mbggenerated
     */
    public void setShifouNeixiu(String shifouNeixiu) {
        this.shifouNeixiu = shifouNeixiu == null ? null : shifouNeixiu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_spareparts.danjia
     *
     * @return the value of lossaccessment_spareparts.danjia
     *
     * @mbggenerated
     */
    public BigDecimal getDanjia() {
        return danjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_spareparts.danjia
     *
     * @param danjia the value for lossaccessment_spareparts.danjia
     *
     * @mbggenerated
     */
    public void setDanjia(BigDecimal danjia) {
        this.danjia = danjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_spareparts.shuliang
     *
     * @return the value of lossaccessment_spareparts.shuliang
     *
     * @mbggenerated
     */
    public Long getShuliang() {
        return shuliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_spareparts.shuliang
     *
     * @param shuliang the value for lossaccessment_spareparts.shuliang
     *
     * @mbggenerated
     */
    public void setShuliang(Long shuliang) {
        this.shuliang = shuliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_spareparts.xiaoji_jine
     *
     * @return the value of lossaccessment_spareparts.xiaoji_jine
     *
     * @mbggenerated
     */
    public BigDecimal getXiaojiJine() {
        return xiaojiJine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_spareparts.xiaoji_jine
     *
     * @param xiaojiJine the value for lossaccessment_spareparts.xiaoji_jine
     *
     * @mbggenerated
     */
    public void setXiaojiJine(BigDecimal xiaojiJine) {
        this.xiaojiJine = xiaojiJine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment_spareparts.beizhu
     *
     * @return the value of lossaccessment_spareparts.beizhu
     *
     * @mbggenerated
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment_spareparts.beizhu
     *
     * @param beizhu the value for lossaccessment_spareparts.beizhu
     *
     * @mbggenerated
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu == null ? null : beizhu.trim();
    }
}