package com.yanglin.model;

import java.math.BigDecimal;
import java.util.Date;

public class Lossaccessment {
    
    private String dingsunxianzhong;
    public String getDingsunxianzhong() {
        return dingsunxianzhong;
    }

    public void setDingsunxianzhong(String dingsunxianzhong) {
        this.dingsunxianzhong = dingsunxianzhong;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.baoanhao
     *
     * @mbggenerated
     */
    private String baoanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.chepaihao
     *
     * @mbggenerated
     */
    private String chepaihao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.baodanhao
     *
     * @mbggenerated
     */
    private String baodanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.xiulichang_mingcheng
     *
     * @mbggenerated
     */
    private String xiulichangMingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.xiulichang_zizhi
     *
     * @mbggenerated
     */
    private String xiulichangZizhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.xiulichang_leixing
     *
     * @mbggenerated
     */
    private String xiulichangLeixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.dingsunren_mingcheng
     *
     * @mbggenerated
     */
    private String dingsunrenMingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.dingsunren_daima
     *
     * @mbggenerated
     */
    private String dingsunrenDaima;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.dingsunjigou_mingcheng
     *
     * @mbggenerated
     */
    private String dingsunjigouMingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.dingsunjigou_daima
     *
     * @mbggenerated
     */
    private String dingsunjigouDaima;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.dingsun_leixing
     *
     * @mbggenerated
     */
    private String dingsunLeixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.dingsun_shijian
     *
     * @mbggenerated
     */
    private Date dingsunShijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.dingsun_hejijine
     *
     * @mbggenerated
     */
    private BigDecimal dingsunHejijine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.dingsun_zongcanzhijine
     *
     * @mbggenerated
     */
    private BigDecimal dingsunZongcanzhijine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.shijiufei
     *
     * @mbggenerated
     */
    private BigDecimal shijiufei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.baoxianleixing_xianbie
     *
     * @mbggenerated
     */
    private String baoxianleixingXianbie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.qibao_shijian
     *
     * @mbggenerated
     */
    private Date qibaoShijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lossaccessment.zhongbao_shijian
     *
     * @mbggenerated
     */
    private Date zhongbaoShijian;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.baoanhao
     *
     * @return the value of lossaccessment.baoanhao
     *
     * @mbggenerated
     */
    public String getBaoanhao() {
        return baoanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.baoanhao
     *
     * @param baoanhao the value for lossaccessment.baoanhao
     *
     * @mbggenerated
     */
    public void setBaoanhao(String baoanhao) {
        this.baoanhao = baoanhao == null ? null : baoanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.chepaihao
     *
     * @return the value of lossaccessment.chepaihao
     *
     * @mbggenerated
     */
    public String getChepaihao() {
        return chepaihao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.chepaihao
     *
     * @param chepaihao the value for lossaccessment.chepaihao
     *
     * @mbggenerated
     */
    public void setChepaihao(String chepaihao) {
        this.chepaihao = chepaihao == null ? null : chepaihao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.baodanhao
     *
     * @return the value of lossaccessment.baodanhao
     *
     * @mbggenerated
     */
    public String getBaodanhao() {
        return baodanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.baodanhao
     *
     * @param baodanhao the value for lossaccessment.baodanhao
     *
     * @mbggenerated
     */
    public void setBaodanhao(String baodanhao) {
        this.baodanhao = baodanhao == null ? null : baodanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.xiulichang_mingcheng
     *
     * @return the value of lossaccessment.xiulichang_mingcheng
     *
     * @mbggenerated
     */
    public String getXiulichangMingcheng() {
        return xiulichangMingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.xiulichang_mingcheng
     *
     * @param xiulichangMingcheng the value for lossaccessment.xiulichang_mingcheng
     *
     * @mbggenerated
     */
    public void setXiulichangMingcheng(String xiulichangMingcheng) {
        this.xiulichangMingcheng = xiulichangMingcheng == null ? null : xiulichangMingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.xiulichang_zizhi
     *
     * @return the value of lossaccessment.xiulichang_zizhi
     *
     * @mbggenerated
     */
    public String getXiulichangZizhi() {
        return xiulichangZizhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.xiulichang_zizhi
     *
     * @param xiulichangZizhi the value for lossaccessment.xiulichang_zizhi
     *
     * @mbggenerated
     */
    public void setXiulichangZizhi(String xiulichangZizhi) {
        this.xiulichangZizhi = xiulichangZizhi == null ? null : xiulichangZizhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.xiulichang_leixing
     *
     * @return the value of lossaccessment.xiulichang_leixing
     *
     * @mbggenerated
     */
    public String getXiulichangLeixing() {
        return xiulichangLeixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.xiulichang_leixing
     *
     * @param xiulichangLeixing the value for lossaccessment.xiulichang_leixing
     *
     * @mbggenerated
     */
    public void setXiulichangLeixing(String xiulichangLeixing) {
        this.xiulichangLeixing = xiulichangLeixing == null ? null : xiulichangLeixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.dingsunren_mingcheng
     *
     * @return the value of lossaccessment.dingsunren_mingcheng
     *
     * @mbggenerated
     */
    public String getDingsunrenMingcheng() {
        return dingsunrenMingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.dingsunren_mingcheng
     *
     * @param dingsunrenMingcheng the value for lossaccessment.dingsunren_mingcheng
     *
     * @mbggenerated
     */
    public void setDingsunrenMingcheng(String dingsunrenMingcheng) {
        this.dingsunrenMingcheng = dingsunrenMingcheng == null ? null : dingsunrenMingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.dingsunren_daima
     *
     * @return the value of lossaccessment.dingsunren_daima
     *
     * @mbggenerated
     */
    public String getDingsunrenDaima() {
        return dingsunrenDaima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.dingsunren_daima
     *
     * @param dingsunrenDaima the value for lossaccessment.dingsunren_daima
     *
     * @mbggenerated
     */
    public void setDingsunrenDaima(String dingsunrenDaima) {
        this.dingsunrenDaima = dingsunrenDaima == null ? null : dingsunrenDaima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.dingsunjigou_mingcheng
     *
     * @return the value of lossaccessment.dingsunjigou_mingcheng
     *
     * @mbggenerated
     */
    public String getDingsunjigouMingcheng() {
        return dingsunjigouMingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.dingsunjigou_mingcheng
     *
     * @param dingsunjigouMingcheng the value for lossaccessment.dingsunjigou_mingcheng
     *
     * @mbggenerated
     */
    public void setDingsunjigouMingcheng(String dingsunjigouMingcheng) {
        this.dingsunjigouMingcheng = dingsunjigouMingcheng == null ? null : dingsunjigouMingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.dingsunjigou_daima
     *
     * @return the value of lossaccessment.dingsunjigou_daima
     *
     * @mbggenerated
     */
    public String getDingsunjigouDaima() {
        return dingsunjigouDaima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.dingsunjigou_daima
     *
     * @param dingsunjigouDaima the value for lossaccessment.dingsunjigou_daima
     *
     * @mbggenerated
     */
    public void setDingsunjigouDaima(String dingsunjigouDaima) {
        this.dingsunjigouDaima = dingsunjigouDaima == null ? null : dingsunjigouDaima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.dingsun_leixing
     *
     * @return the value of lossaccessment.dingsun_leixing
     *
     * @mbggenerated
     */
    public String getDingsunLeixing() {
        return dingsunLeixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.dingsun_leixing
     *
     * @param dingsunLeixing the value for lossaccessment.dingsun_leixing
     *
     * @mbggenerated
     */
    public void setDingsunLeixing(String dingsunLeixing) {
        this.dingsunLeixing = dingsunLeixing == null ? null : dingsunLeixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.dingsun_shijian
     *
     * @return the value of lossaccessment.dingsun_shijian
     *
     * @mbggenerated
     */
    public Date getDingsunShijian() {
        return dingsunShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.dingsun_shijian
     *
     * @param dingsunShijian the value for lossaccessment.dingsun_shijian
     *
     * @mbggenerated
     */
    public void setDingsunShijian(Date dingsunShijian) {
        this.dingsunShijian = dingsunShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.dingsun_hejijine
     *
     * @return the value of lossaccessment.dingsun_hejijine
     *
     * @mbggenerated
     */
    public BigDecimal getDingsunHejijine() {
        return dingsunHejijine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.dingsun_hejijine
     *
     * @param dingsunHejijine the value for lossaccessment.dingsun_hejijine
     *
     * @mbggenerated
     */
    public void setDingsunHejijine(BigDecimal dingsunHejijine) {
        this.dingsunHejijine = dingsunHejijine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.dingsun_zongcanzhijine
     *
     * @return the value of lossaccessment.dingsun_zongcanzhijine
     *
     * @mbggenerated
     */
    public BigDecimal getDingsunZongcanzhijine() {
        return dingsunZongcanzhijine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.dingsun_zongcanzhijine
     *
     * @param dingsunZongcanzhijine the value for lossaccessment.dingsun_zongcanzhijine
     *
     * @mbggenerated
     */
    public void setDingsunZongcanzhijine(BigDecimal dingsunZongcanzhijine) {
        this.dingsunZongcanzhijine = dingsunZongcanzhijine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.shijiufei
     *
     * @return the value of lossaccessment.shijiufei
     *
     * @mbggenerated
     */
    public BigDecimal getShijiufei() {
        return shijiufei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.shijiufei
     *
     * @param shijiufei the value for lossaccessment.shijiufei
     *
     * @mbggenerated
     */
    public void setShijiufei(BigDecimal shijiufei) {
        this.shijiufei = shijiufei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.baoxianleixing_xianbie
     *
     * @return the value of lossaccessment.baoxianleixing_xianbie
     *
     * @mbggenerated
     */
    public String getBaoxianleixingXianbie() {
        return baoxianleixingXianbie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.baoxianleixing_xianbie
     *
     * @param baoxianleixingXianbie the value for lossaccessment.baoxianleixing_xianbie
     *
     * @mbggenerated
     */
    public void setBaoxianleixingXianbie(String baoxianleixingXianbie) {
        this.baoxianleixingXianbie = baoxianleixingXianbie == null ? null : baoxianleixingXianbie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.qibao_shijian
     *
     * @return the value of lossaccessment.qibao_shijian
     *
     * @mbggenerated
     */
    public Date getQibaoShijian() {
        return qibaoShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.qibao_shijian
     *
     * @param qibaoShijian the value for lossaccessment.qibao_shijian
     *
     * @mbggenerated
     */
    public void setQibaoShijian(Date qibaoShijian) {
        this.qibaoShijian = qibaoShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lossaccessment.zhongbao_shijian
     *
     * @return the value of lossaccessment.zhongbao_shijian
     *
     * @mbggenerated
     */
    public Date getZhongbaoShijian() {
        return zhongbaoShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lossaccessment.zhongbao_shijian
     *
     * @param zhongbaoShijian the value for lossaccessment.zhongbao_shijian
     *
     * @mbggenerated
     */
    public void setZhongbaoShijian(Date zhongbaoShijian) {
        this.zhongbaoShijian = zhongbaoShijian;
    }
}