package com.yanglin.model;

import java.util.Date;

public class PolicyCategory {
    
    private double xinchegouzhijia;
    public double getXinchegouzhijia() {
        return xinchegouzhijia;
    }

    public void setXinchegouzhijia(double xinchegouzhijia) {
        this.xinchegouzhijia = xinchegouzhijia;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_category.baodanhao
     *
     * @mbggenerated
     */
    private String baodanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_category.baodan_leixing
     *
     * @mbggenerated
     */
    private String baodanLeixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_category.beibaoxianren_kehuleixing
     *
     * @mbggenerated
     */
    private String beibaoxianrenKehuleixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_category.suoshuxingzhi
     *
     * @mbggenerated
     */
    private String suoshuxingzhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_category.shiyongxingzhi
     *
     * @mbggenerated
     */
    private String shiyongxingzhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_category.xingshiquyu
     *
     * @mbggenerated
     */
    private String xingshiquyu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_category.qibao_shijian
     *
     * @mbggenerated
     */
    private Date qibaoShijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_category.zhongbao_shijian
     *
     * @mbggenerated
     */
    private Date zhongbaoShijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_category.toubaoren_mingcheng
     *
     * @mbggenerated
     */
    private String toubaorenMingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_category.zhiding_jiashiyuanxingming
     *
     * @mbggenerated
     */
    private String zhidingJiashiyuanxingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_category.chudanjigou
     *
     * @mbggenerated
     */
    private String chudanjigou;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_category.pigaishijian
     *
     * @mbggenerated
     */
    private String pigaishijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_category.shifou_toubaoxinzengshebei
     *
     * @mbggenerated
     */
    private String shifouToubaoxinzengshebei;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_category.baodanhao
     *
     * @return the value of policy_category.baodanhao
     *
     * @mbggenerated
     */
    public String getBaodanhao() {
        return baodanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_category.baodanhao
     *
     * @param baodanhao the value for policy_category.baodanhao
     *
     * @mbggenerated
     */
    public void setBaodanhao(String baodanhao) {
        this.baodanhao = baodanhao == null ? null : baodanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_category.baodan_leixing
     *
     * @return the value of policy_category.baodan_leixing
     *
     * @mbggenerated
     */
    public String getBaodanLeixing() {
        return baodanLeixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_category.baodan_leixing
     *
     * @param baodanLeixing the value for policy_category.baodan_leixing
     *
     * @mbggenerated
     */
    public void setBaodanLeixing(String baodanLeixing) {
        this.baodanLeixing = baodanLeixing == null ? null : baodanLeixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_category.beibaoxianren_kehuleixing
     *
     * @return the value of policy_category.beibaoxianren_kehuleixing
     *
     * @mbggenerated
     */
    public String getBeibaoxianrenKehuleixing() {
        return beibaoxianrenKehuleixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_category.beibaoxianren_kehuleixing
     *
     * @param beibaoxianrenKehuleixing the value for policy_category.beibaoxianren_kehuleixing
     *
     * @mbggenerated
     */
    public void setBeibaoxianrenKehuleixing(String beibaoxianrenKehuleixing) {
        this.beibaoxianrenKehuleixing = beibaoxianrenKehuleixing == null ? null : beibaoxianrenKehuleixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_category.suoshuxingzhi
     *
     * @return the value of policy_category.suoshuxingzhi
     *
     * @mbggenerated
     */
    public String getSuoshuxingzhi() {
        return suoshuxingzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_category.suoshuxingzhi
     *
     * @param suoshuxingzhi the value for policy_category.suoshuxingzhi
     *
     * @mbggenerated
     */
    public void setSuoshuxingzhi(String suoshuxingzhi) {
        this.suoshuxingzhi = suoshuxingzhi == null ? null : suoshuxingzhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_category.shiyongxingzhi
     *
     * @return the value of policy_category.shiyongxingzhi
     *
     * @mbggenerated
     */
    public String getShiyongxingzhi() {
        return shiyongxingzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_category.shiyongxingzhi
     *
     * @param shiyongxingzhi the value for policy_category.shiyongxingzhi
     *
     * @mbggenerated
     */
    public void setShiyongxingzhi(String shiyongxingzhi) {
        this.shiyongxingzhi = shiyongxingzhi == null ? null : shiyongxingzhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_category.xingshiquyu
     *
     * @return the value of policy_category.xingshiquyu
     *
     * @mbggenerated
     */
    public String getXingshiquyu() {
        return xingshiquyu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_category.xingshiquyu
     *
     * @param xingshiquyu the value for policy_category.xingshiquyu
     *
     * @mbggenerated
     */
    public void setXingshiquyu(String xingshiquyu) {
        this.xingshiquyu = xingshiquyu == null ? null : xingshiquyu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_category.qibao_shijian
     *
     * @return the value of policy_category.qibao_shijian
     *
     * @mbggenerated
     */
    public Date getQibaoShijian() {
        return qibaoShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_category.qibao_shijian
     *
     * @param qibaoShijian the value for policy_category.qibao_shijian
     *
     * @mbggenerated
     */
    public void setQibaoShijian(Date qibaoShijian) {
        this.qibaoShijian = qibaoShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_category.zhongbao_shijian
     *
     * @return the value of policy_category.zhongbao_shijian
     *
     * @mbggenerated
     */
    public Date getZhongbaoShijian() {
        return zhongbaoShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_category.zhongbao_shijian
     *
     * @param zhongbaoShijian the value for policy_category.zhongbao_shijian
     *
     * @mbggenerated
     */
    public void setZhongbaoShijian(Date zhongbaoShijian) {
        this.zhongbaoShijian = zhongbaoShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_category.toubaoren_mingcheng
     *
     * @return the value of policy_category.toubaoren_mingcheng
     *
     * @mbggenerated
     */
    public String getToubaorenMingcheng() {
        return toubaorenMingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_category.toubaoren_mingcheng
     *
     * @param toubaorenMingcheng the value for policy_category.toubaoren_mingcheng
     *
     * @mbggenerated
     */
    public void setToubaorenMingcheng(String toubaorenMingcheng) {
        this.toubaorenMingcheng = toubaorenMingcheng == null ? null : toubaorenMingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_category.zhiding_jiashiyuanxingming
     *
     * @return the value of policy_category.zhiding_jiashiyuanxingming
     *
     * @mbggenerated
     */
    public String getZhidingJiashiyuanxingming() {
        return zhidingJiashiyuanxingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_category.zhiding_jiashiyuanxingming
     *
     * @param zhidingJiashiyuanxingming the value for policy_category.zhiding_jiashiyuanxingming
     *
     * @mbggenerated
     */
    public void setZhidingJiashiyuanxingming(String zhidingJiashiyuanxingming) {
        this.zhidingJiashiyuanxingming = zhidingJiashiyuanxingming == null ? null : zhidingJiashiyuanxingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_category.chudanjigou
     *
     * @return the value of policy_category.chudanjigou
     *
     * @mbggenerated
     */
    public String getChudanjigou() {
        return chudanjigou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_category.chudanjigou
     *
     * @param chudanjigou the value for policy_category.chudanjigou
     *
     * @mbggenerated
     */
    public void setChudanjigou(String chudanjigou) {
        this.chudanjigou = chudanjigou == null ? null : chudanjigou.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_category.pigaishijian
     *
     * @return the value of policy_category.pigaishijian
     *
     * @mbggenerated
     */
    public String getPigaishijian() {
        return pigaishijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_category.pigaishijian
     *
     * @param pigaishijian the value for policy_category.pigaishijian
     *
     * @mbggenerated
     */
    public void setPigaishijian(String pigaishijian) {
        this.pigaishijian = pigaishijian == null ? null : pigaishijian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_category.shifou_toubaoxinzengshebei
     *
     * @return the value of policy_category.shifou_toubaoxinzengshebei
     *
     * @mbggenerated
     */
    public String getShifouToubaoxinzengshebei() {
        return shifouToubaoxinzengshebei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_category.shifou_toubaoxinzengshebei
     *
     * @param shifouToubaoxinzengshebei the value for policy_category.shifou_toubaoxinzengshebei
     *
     * @mbggenerated
     */
    public void setShifouToubaoxinzengshebei(String shifouToubaoxinzengshebei) {
        this.shifouToubaoxinzengshebei = shifouToubaoxinzengshebei == null ? null : shifouToubaoxinzengshebei.trim();
    }

}