package com.yanglin.model;

import java.math.BigDecimal;
import java.util.Date;

public class PolicyRiskclass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_riskclass.baodanhao
     *
     * @mbggenerated
     */
    private String baodanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_riskclass.xianbiemingcheng
     *
     * @mbggenerated
     */
    private String xianbiemingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_riskclass.qibao_shijian
     *
     * @mbggenerated
     */
    private Date qibaoShijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_riskclass.zhongbao_shijian
     *
     * @mbggenerated
     */
    private Date zhongbaoShijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_riskclass.mianpeilv
     *
     * @mbggenerated
     */
    private BigDecimal mianpeilv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policy_riskclass.mianpeie
     *
     * @mbggenerated
     */
    private BigDecimal mianpeie;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_riskclass.baodanhao
     *
     * @return the value of policy_riskclass.baodanhao
     *
     * @mbggenerated
     */
    public String getBaodanhao() {
        return baodanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_riskclass.baodanhao
     *
     * @param baodanhao the value for policy_riskclass.baodanhao
     *
     * @mbggenerated
     */
    public void setBaodanhao(String baodanhao) {
        this.baodanhao = baodanhao == null ? null : baodanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_riskclass.xianbiemingcheng
     *
     * @return the value of policy_riskclass.xianbiemingcheng
     *
     * @mbggenerated
     */
    public String getXianbiemingcheng() {
        return xianbiemingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_riskclass.xianbiemingcheng
     *
     * @param xianbiemingcheng the value for policy_riskclass.xianbiemingcheng
     *
     * @mbggenerated
     */
    public void setXianbiemingcheng(String xianbiemingcheng) {
        this.xianbiemingcheng = xianbiemingcheng == null ? null : xianbiemingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_riskclass.qibao_shijian
     *
     * @return the value of policy_riskclass.qibao_shijian
     *
     * @mbggenerated
     */
    public Date getQibaoShijian() {
        return qibaoShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_riskclass.qibao_shijian
     *
     * @param qibaoShijian the value for policy_riskclass.qibao_shijian
     *
     * @mbggenerated
     */
    public void setQibaoShijian(Date qibaoShijian) {
        this.qibaoShijian = qibaoShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_riskclass.zhongbao_shijian
     *
     * @return the value of policy_riskclass.zhongbao_shijian
     *
     * @mbggenerated
     */
    public Date getZhongbaoShijian() {
        return zhongbaoShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_riskclass.zhongbao_shijian
     *
     * @param zhongbaoShijian the value for policy_riskclass.zhongbao_shijian
     *
     * @mbggenerated
     */
    public void setZhongbaoShijian(Date zhongbaoShijian) {
        this.zhongbaoShijian = zhongbaoShijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_riskclass.mianpeilv
     *
     * @return the value of policy_riskclass.mianpeilv
     *
     * @mbggenerated
     */
    public BigDecimal getMianpeilv() {
        return mianpeilv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_riskclass.mianpeilv
     *
     * @param mianpeilv the value for policy_riskclass.mianpeilv
     *
     * @mbggenerated
     */
    public void setMianpeilv(BigDecimal mianpeilv) {
        this.mianpeilv = mianpeilv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policy_riskclass.mianpeie
     *
     * @return the value of policy_riskclass.mianpeie
     *
     * @mbggenerated
     */
    public BigDecimal getMianpeie() {
        return mianpeie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policy_riskclass.mianpeie
     *
     * @param mianpeie the value for policy_riskclass.mianpeie
     *
     * @mbggenerated
     */
    public void setMianpeie(BigDecimal mianpeie) {
        this.mianpeie = mianpeie;
    }
}