package com.yanglin.model;

public class Reportinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.baoanhao
     *
     * @mbggenerated
     */
    private String baoanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.baodanhao
     *
     * @mbggenerated
     */
    private String baodanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.anjianlaiyuan
     *
     * @mbggenerated
     */
    private String anjianlaiyuan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.lishi_chuxiancishu
     *
     * @mbggenerated
     */
    private String lishiChuxiancishu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.guanlian_baoanhao
     *
     * @mbggenerated
     */
    private String guanlianBaoanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.peian_leixing
     *
     * @mbggenerated
     */
    private String peianLeixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.baoanren
     *
     * @mbggenerated
     */
    private String baoanren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.baoanren_dianhua
     *
     * @mbggenerated
     */
    private String baoanrenDianhua;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.chuxianshijian
     *
     * @mbggenerated
     */
    private String chuxianshijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.baoanshijian
     *
     * @mbggenerated
     */
    private String baoanshijian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.shifou_xianchangbaoan
     *
     * @mbggenerated
     */
    private String shifouXianchangbaoan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.chuxiandidian
     *
     * @mbggenerated
     */
    private String chuxiandidian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.chuxian_yuanyin
     *
     * @mbggenerated
     */
    private String chuxianYuanyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.chuxian_jingguo
     *
     * @mbggenerated
     */
    private String chuxianJingguo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.shifou_yidichuxian
     *
     * @mbggenerated
     */
    private String shifouYidichuxian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.baoan_jiashiyuan
     *
     * @mbggenerated
     */
    private String baoanJiashiyuan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.baoan_jiashiyuan_xingbie
     *
     * @mbggenerated
     */
    private String baoanJiashiyuanXingbie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.shiguzeren
     *
     * @mbggenerated
     */
    private String shiguzeren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.shiguleixing
     *
     * @mbggenerated
     */
    private String shiguleixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.baoanren_shifou_beibaoxianren
     *
     * @mbggenerated
     */
    private String baoanrenShifouBeibaoxianren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.beibaoxianren
     *
     * @mbggenerated
     */
    private String beibaoxianren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reportinfo.beibaoxianren_dianhua
     *
     * @mbggenerated
     */
    private String beibaoxianrenDianhua;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.baoanhao
     *
     * @return the value of reportinfo.baoanhao
     *
     * @mbggenerated
     */
    public String getBaoanhao() {
        return baoanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.baoanhao
     *
     * @param baoanhao the value for reportinfo.baoanhao
     *
     * @mbggenerated
     */
    public void setBaoanhao(String baoanhao) {
        this.baoanhao = baoanhao == null ? null : baoanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.baodanhao
     *
     * @return the value of reportinfo.baodanhao
     *
     * @mbggenerated
     */
    public String getBaodanhao() {
        return baodanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.baodanhao
     *
     * @param baodanhao the value for reportinfo.baodanhao
     *
     * @mbggenerated
     */
    public void setBaodanhao(String baodanhao) {
        this.baodanhao = baodanhao == null ? null : baodanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.anjianlaiyuan
     *
     * @return the value of reportinfo.anjianlaiyuan
     *
     * @mbggenerated
     */
    public String getAnjianlaiyuan() {
        return anjianlaiyuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.anjianlaiyuan
     *
     * @param anjianlaiyuan the value for reportinfo.anjianlaiyuan
     *
     * @mbggenerated
     */
    public void setAnjianlaiyuan(String anjianlaiyuan) {
        this.anjianlaiyuan = anjianlaiyuan == null ? null : anjianlaiyuan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.lishi_chuxiancishu
     *
     * @return the value of reportinfo.lishi_chuxiancishu
     *
     * @mbggenerated
     */
    public String getLishiChuxiancishu() {
        return lishiChuxiancishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.lishi_chuxiancishu
     *
     * @param lishiChuxiancishu the value for reportinfo.lishi_chuxiancishu
     *
     * @mbggenerated
     */
    public void setLishiChuxiancishu(String lishiChuxiancishu) {
        this.lishiChuxiancishu = lishiChuxiancishu == null ? null : lishiChuxiancishu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.guanlian_baoanhao
     *
     * @return the value of reportinfo.guanlian_baoanhao
     *
     * @mbggenerated
     */
    public String getGuanlianBaoanhao() {
        return guanlianBaoanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.guanlian_baoanhao
     *
     * @param guanlianBaoanhao the value for reportinfo.guanlian_baoanhao
     *
     * @mbggenerated
     */
    public void setGuanlianBaoanhao(String guanlianBaoanhao) {
        this.guanlianBaoanhao = guanlianBaoanhao == null ? null : guanlianBaoanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.peian_leixing
     *
     * @return the value of reportinfo.peian_leixing
     *
     * @mbggenerated
     */
    public String getPeianLeixing() {
        return peianLeixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.peian_leixing
     *
     * @param peianLeixing the value for reportinfo.peian_leixing
     *
     * @mbggenerated
     */
    public void setPeianLeixing(String peianLeixing) {
        this.peianLeixing = peianLeixing == null ? null : peianLeixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.baoanren
     *
     * @return the value of reportinfo.baoanren
     *
     * @mbggenerated
     */
    public String getBaoanren() {
        return baoanren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.baoanren
     *
     * @param baoanren the value for reportinfo.baoanren
     *
     * @mbggenerated
     */
    public void setBaoanren(String baoanren) {
        this.baoanren = baoanren == null ? null : baoanren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.baoanren_dianhua
     *
     * @return the value of reportinfo.baoanren_dianhua
     *
     * @mbggenerated
     */
    public String getBaoanrenDianhua() {
        return baoanrenDianhua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.baoanren_dianhua
     *
     * @param baoanrenDianhua the value for reportinfo.baoanren_dianhua
     *
     * @mbggenerated
     */
    public void setBaoanrenDianhua(String baoanrenDianhua) {
        this.baoanrenDianhua = baoanrenDianhua == null ? null : baoanrenDianhua.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.chuxianshijian
     *
     * @return the value of reportinfo.chuxianshijian
     *
     * @mbggenerated
     */
    public String getChuxianshijian() {
        return chuxianshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.chuxianshijian
     *
     * @param chuxianshijian the value for reportinfo.chuxianshijian
     *
     * @mbggenerated
     */
    public void setChuxianshijian(String chuxianshijian) {
        this.chuxianshijian = chuxianshijian == null ? null : chuxianshijian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.baoanshijian
     *
     * @return the value of reportinfo.baoanshijian
     *
     * @mbggenerated
     */
    public String getBaoanshijian() {
        return baoanshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.baoanshijian
     *
     * @param baoanshijian the value for reportinfo.baoanshijian
     *
     * @mbggenerated
     */
    public void setBaoanshijian(String baoanshijian) {
        this.baoanshijian = baoanshijian == null ? null : baoanshijian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.shifou_xianchangbaoan
     *
     * @return the value of reportinfo.shifou_xianchangbaoan
     *
     * @mbggenerated
     */
    public String getShifouXianchangbaoan() {
        return shifouXianchangbaoan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.shifou_xianchangbaoan
     *
     * @param shifouXianchangbaoan the value for reportinfo.shifou_xianchangbaoan
     *
     * @mbggenerated
     */
    public void setShifouXianchangbaoan(String shifouXianchangbaoan) {
        this.shifouXianchangbaoan = shifouXianchangbaoan == null ? null : shifouXianchangbaoan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.chuxiandidian
     *
     * @return the value of reportinfo.chuxiandidian
     *
     * @mbggenerated
     */
    public String getChuxiandidian() {
        return chuxiandidian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.chuxiandidian
     *
     * @param chuxiandidian the value for reportinfo.chuxiandidian
     *
     * @mbggenerated
     */
    public void setChuxiandidian(String chuxiandidian) {
        this.chuxiandidian = chuxiandidian == null ? null : chuxiandidian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.chuxian_yuanyin
     *
     * @return the value of reportinfo.chuxian_yuanyin
     *
     * @mbggenerated
     */
    public String getChuxianYuanyin() {
        return chuxianYuanyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.chuxian_yuanyin
     *
     * @param chuxianYuanyin the value for reportinfo.chuxian_yuanyin
     *
     * @mbggenerated
     */
    public void setChuxianYuanyin(String chuxianYuanyin) {
        this.chuxianYuanyin = chuxianYuanyin == null ? null : chuxianYuanyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.chuxian_jingguo
     *
     * @return the value of reportinfo.chuxian_jingguo
     *
     * @mbggenerated
     */
    public String getChuxianJingguo() {
        return chuxianJingguo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.chuxian_jingguo
     *
     * @param chuxianJingguo the value for reportinfo.chuxian_jingguo
     *
     * @mbggenerated
     */
    public void setChuxianJingguo(String chuxianJingguo) {
        this.chuxianJingguo = chuxianJingguo == null ? null : chuxianJingguo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.shifou_yidichuxian
     *
     * @return the value of reportinfo.shifou_yidichuxian
     *
     * @mbggenerated
     */
    public String getShifouYidichuxian() {
        return shifouYidichuxian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.shifou_yidichuxian
     *
     * @param shifouYidichuxian the value for reportinfo.shifou_yidichuxian
     *
     * @mbggenerated
     */
    public void setShifouYidichuxian(String shifouYidichuxian) {
        this.shifouYidichuxian = shifouYidichuxian == null ? null : shifouYidichuxian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.baoan_jiashiyuan
     *
     * @return the value of reportinfo.baoan_jiashiyuan
     *
     * @mbggenerated
     */
    public String getBaoanJiashiyuan() {
        return baoanJiashiyuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.baoan_jiashiyuan
     *
     * @param baoanJiashiyuan the value for reportinfo.baoan_jiashiyuan
     *
     * @mbggenerated
     */
    public void setBaoanJiashiyuan(String baoanJiashiyuan) {
        this.baoanJiashiyuan = baoanJiashiyuan == null ? null : baoanJiashiyuan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.baoan_jiashiyuan_xingbie
     *
     * @return the value of reportinfo.baoan_jiashiyuan_xingbie
     *
     * @mbggenerated
     */
    public String getBaoanJiashiyuanXingbie() {
        return baoanJiashiyuanXingbie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.baoan_jiashiyuan_xingbie
     *
     * @param baoanJiashiyuanXingbie the value for reportinfo.baoan_jiashiyuan_xingbie
     *
     * @mbggenerated
     */
    public void setBaoanJiashiyuanXingbie(String baoanJiashiyuanXingbie) {
        this.baoanJiashiyuanXingbie = baoanJiashiyuanXingbie == null ? null : baoanJiashiyuanXingbie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.shiguzeren
     *
     * @return the value of reportinfo.shiguzeren
     *
     * @mbggenerated
     */
    public String getShiguzeren() {
        return shiguzeren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.shiguzeren
     *
     * @param shiguzeren the value for reportinfo.shiguzeren
     *
     * @mbggenerated
     */
    public void setShiguzeren(String shiguzeren) {
        this.shiguzeren = shiguzeren == null ? null : shiguzeren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.shiguleixing
     *
     * @return the value of reportinfo.shiguleixing
     *
     * @mbggenerated
     */
    public String getShiguleixing() {
        return shiguleixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.shiguleixing
     *
     * @param shiguleixing the value for reportinfo.shiguleixing
     *
     * @mbggenerated
     */
    public void setShiguleixing(String shiguleixing) {
        this.shiguleixing = shiguleixing == null ? null : shiguleixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.baoanren_shifou_beibaoxianren
     *
     * @return the value of reportinfo.baoanren_shifou_beibaoxianren
     *
     * @mbggenerated
     */
    public String getBaoanrenShifouBeibaoxianren() {
        return baoanrenShifouBeibaoxianren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.baoanren_shifou_beibaoxianren
     *
     * @param baoanrenShifouBeibaoxianren the value for reportinfo.baoanren_shifou_beibaoxianren
     *
     * @mbggenerated
     */
    public void setBaoanrenShifouBeibaoxianren(String baoanrenShifouBeibaoxianren) {
        this.baoanrenShifouBeibaoxianren = baoanrenShifouBeibaoxianren == null ? null : baoanrenShifouBeibaoxianren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.beibaoxianren
     *
     * @return the value of reportinfo.beibaoxianren
     *
     * @mbggenerated
     */
    public String getBeibaoxianren() {
        return beibaoxianren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.beibaoxianren
     *
     * @param beibaoxianren the value for reportinfo.beibaoxianren
     *
     * @mbggenerated
     */
    public void setBeibaoxianren(String beibaoxianren) {
        this.beibaoxianren = beibaoxianren == null ? null : beibaoxianren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reportinfo.beibaoxianren_dianhua
     *
     * @return the value of reportinfo.beibaoxianren_dianhua
     *
     * @mbggenerated
     */
    public String getBeibaoxianrenDianhua() {
        return beibaoxianrenDianhua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reportinfo.beibaoxianren_dianhua
     *
     * @param beibaoxianrenDianhua the value for reportinfo.beibaoxianren_dianhua
     *
     * @mbggenerated
     */
    public void setBeibaoxianrenDianhua(String beibaoxianrenDianhua) {
        this.beibaoxianrenDianhua = beibaoxianrenDianhua == null ? null : beibaoxianrenDianhua.trim();
    }
}