package com.yanglin.model;

import java.util.Date;

public class SurveyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.baoanhao
     *
     * @mbggenerated
     */
    private String baoanhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.peifufangshi
     *
     * @mbggenerated
     */
    private String peifufangshi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.zerenxishu
     *
     * @mbggenerated
     */
    private String zerenxishu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.xieshangjiakoubili
     *
     * @mbggenerated
     */
    private String xieshangjiakoubili;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.lipeileixing
     *
     * @mbggenerated
     */
    private String lipeileixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.chuxianyuanyin
     *
     * @mbggenerated
     */
    private String chuxianyuanyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.shiguleixing
     *
     * @mbggenerated
     */
    private String shiguleixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.disanfang_cheliangshu
     *
     * @mbggenerated
     */
    private String disanfangCheliangshu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.chakan_daichakanren
     *
     * @mbggenerated
     */
    private String chakanDaichakanren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.chakan_jigoumingcheng
     *
     * @mbggenerated
     */
    private String chakanJigoumingcheng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.chakan_riqi
     *
     * @mbggenerated
     */
    private Date chakanRiqi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.chakan_didian
     *
     * @mbggenerated
     */
    private String chakanDidian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.chakan_leixing
     *
     * @mbggenerated
     */
    private String chakanLeixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.shifou_yidongduanchuli
     *
     * @mbggenerated
     */
    private String shifouYidongduanchuli;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.chakan_baogao
     *
     * @mbggenerated
     */
    private String chakanBaogao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.chepaihao
     *
     * @mbggenerated
     */
    private String chepaihao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.VIN
     *
     * @mbggenerated
     */
    private String vin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.dingsun_chexing
     *
     * @mbggenerated
     */
    private String dingsunChexing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.chezhu_xingming
     *
     * @mbggenerated
     */
    private String chezhuXingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.zhengjian_leixing
     *
     * @mbggenerated
     */
    private String zhengjianLeixing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.chuxian_jiashiyuan
     *
     * @mbggenerated
     */
    private String chuxianJiashiyuan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.jiashizhenghao
     *
     * @mbggenerated
     */
    private String jiashizhenghao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.zhunjiachexing
     *
     * @mbggenerated
     */
    private String zhunjiachexing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.cheliangleibie
     *
     * @mbggenerated
     */
    private String cheliangleibie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.jiashiren_shifou_beibaoren
     *
     * @mbggenerated
     */
    private String jiashirenShifouBeibaoren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.xingshizheng_zhuceriqi
     *
     * @mbggenerated
     */
    private Date xingshizhengZhuceriqi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.xingshizheng_fazhengriqi
     *
     * @mbggenerated
     */
    private Date xingshizhengFazhengriqi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.shifou_baoan_chuxiandidian
     *
     * @mbggenerated
     */
    private String shifouBaoanChuxiandidian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column surveyinfo.chuxiandidian
     *
     * @mbggenerated
     */
    private String chuxiandidian;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.baoanhao
     *
     * @return the value of surveyinfo.baoanhao
     *
     * @mbggenerated
     */
    public String getBaoanhao() {
        return baoanhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.baoanhao
     *
     * @param baoanhao the value for surveyinfo.baoanhao
     *
     * @mbggenerated
     */
    public void setBaoanhao(String baoanhao) {
        this.baoanhao = baoanhao == null ? null : baoanhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.peifufangshi
     *
     * @return the value of surveyinfo.peifufangshi
     *
     * @mbggenerated
     */
    public String getPeifufangshi() {
        return peifufangshi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.peifufangshi
     *
     * @param peifufangshi the value for surveyinfo.peifufangshi
     *
     * @mbggenerated
     */
    public void setPeifufangshi(String peifufangshi) {
        this.peifufangshi = peifufangshi == null ? null : peifufangshi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.zerenxishu
     *
     * @return the value of surveyinfo.zerenxishu
     *
     * @mbggenerated
     */
    public String getZerenxishu() {
        return zerenxishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.zerenxishu
     *
     * @param zerenxishu the value for surveyinfo.zerenxishu
     *
     * @mbggenerated
     */
    public void setZerenxishu(String zerenxishu) {
        this.zerenxishu = zerenxishu == null ? null : zerenxishu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.xieshangjiakoubili
     *
     * @return the value of surveyinfo.xieshangjiakoubili
     *
     * @mbggenerated
     */
    public String getXieshangjiakoubili() {
        return xieshangjiakoubili;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.xieshangjiakoubili
     *
     * @param xieshangjiakoubili the value for surveyinfo.xieshangjiakoubili
     *
     * @mbggenerated
     */
    public void setXieshangjiakoubili(String xieshangjiakoubili) {
        this.xieshangjiakoubili = xieshangjiakoubili == null ? null : xieshangjiakoubili.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.lipeileixing
     *
     * @return the value of surveyinfo.lipeileixing
     *
     * @mbggenerated
     */
    public String getLipeileixing() {
        return lipeileixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.lipeileixing
     *
     * @param lipeileixing the value for surveyinfo.lipeileixing
     *
     * @mbggenerated
     */
    public void setLipeileixing(String lipeileixing) {
        this.lipeileixing = lipeileixing == null ? null : lipeileixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.chuxianyuanyin
     *
     * @return the value of surveyinfo.chuxianyuanyin
     *
     * @mbggenerated
     */
    public String getChuxianyuanyin() {
        return chuxianyuanyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.chuxianyuanyin
     *
     * @param chuxianyuanyin the value for surveyinfo.chuxianyuanyin
     *
     * @mbggenerated
     */
    public void setChuxianyuanyin(String chuxianyuanyin) {
        this.chuxianyuanyin = chuxianyuanyin == null ? null : chuxianyuanyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.shiguleixing
     *
     * @return the value of surveyinfo.shiguleixing
     *
     * @mbggenerated
     */
    public String getShiguleixing() {
        return shiguleixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.shiguleixing
     *
     * @param shiguleixing the value for surveyinfo.shiguleixing
     *
     * @mbggenerated
     */
    public void setShiguleixing(String shiguleixing) {
        this.shiguleixing = shiguleixing == null ? null : shiguleixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.disanfang_cheliangshu
     *
     * @return the value of surveyinfo.disanfang_cheliangshu
     *
     * @mbggenerated
     */
    public String getDisanfangCheliangshu() {
        return disanfangCheliangshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.disanfang_cheliangshu
     *
     * @param disanfangCheliangshu the value for surveyinfo.disanfang_cheliangshu
     *
     * @mbggenerated
     */
    public void setDisanfangCheliangshu(String disanfangCheliangshu) {
        this.disanfangCheliangshu = disanfangCheliangshu == null ? null : disanfangCheliangshu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.chakan_daichakanren
     *
     * @return the value of surveyinfo.chakan_daichakanren
     *
     * @mbggenerated
     */
    public String getChakanDaichakanren() {
        return chakanDaichakanren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.chakan_daichakanren
     *
     * @param chakanDaichakanren the value for surveyinfo.chakan_daichakanren
     *
     * @mbggenerated
     */
    public void setChakanDaichakanren(String chakanDaichakanren) {
        this.chakanDaichakanren = chakanDaichakanren == null ? null : chakanDaichakanren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.chakan_jigoumingcheng
     *
     * @return the value of surveyinfo.chakan_jigoumingcheng
     *
     * @mbggenerated
     */
    public String getChakanJigoumingcheng() {
        return chakanJigoumingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.chakan_jigoumingcheng
     *
     * @param chakanJigoumingcheng the value for surveyinfo.chakan_jigoumingcheng
     *
     * @mbggenerated
     */
    public void setChakanJigoumingcheng(String chakanJigoumingcheng) {
        this.chakanJigoumingcheng = chakanJigoumingcheng == null ? null : chakanJigoumingcheng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.chakan_riqi
     *
     * @return the value of surveyinfo.chakan_riqi
     *
     * @mbggenerated
     */
    public Date getChakanRiqi() {
        return chakanRiqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.chakan_riqi
     *
     * @param chakanRiqi the value for surveyinfo.chakan_riqi
     *
     * @mbggenerated
     */
    public void setChakanRiqi(Date chakanRiqi) {
        this.chakanRiqi = chakanRiqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.chakan_didian
     *
     * @return the value of surveyinfo.chakan_didian
     *
     * @mbggenerated
     */
    public String getChakanDidian() {
        return chakanDidian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.chakan_didian
     *
     * @param chakanDidian the value for surveyinfo.chakan_didian
     *
     * @mbggenerated
     */
    public void setChakanDidian(String chakanDidian) {
        this.chakanDidian = chakanDidian == null ? null : chakanDidian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.chakan_leixing
     *
     * @return the value of surveyinfo.chakan_leixing
     *
     * @mbggenerated
     */
    public String getChakanLeixing() {
        return chakanLeixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.chakan_leixing
     *
     * @param chakanLeixing the value for surveyinfo.chakan_leixing
     *
     * @mbggenerated
     */
    public void setChakanLeixing(String chakanLeixing) {
        this.chakanLeixing = chakanLeixing == null ? null : chakanLeixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.shifou_yidongduanchuli
     *
     * @return the value of surveyinfo.shifou_yidongduanchuli
     *
     * @mbggenerated
     */
    public String getShifouYidongduanchuli() {
        return shifouYidongduanchuli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.shifou_yidongduanchuli
     *
     * @param shifouYidongduanchuli the value for surveyinfo.shifou_yidongduanchuli
     *
     * @mbggenerated
     */
    public void setShifouYidongduanchuli(String shifouYidongduanchuli) {
        this.shifouYidongduanchuli = shifouYidongduanchuli == null ? null : shifouYidongduanchuli.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.chakan_baogao
     *
     * @return the value of surveyinfo.chakan_baogao
     *
     * @mbggenerated
     */
    public String getChakanBaogao() {
        return chakanBaogao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.chakan_baogao
     *
     * @param chakanBaogao the value for surveyinfo.chakan_baogao
     *
     * @mbggenerated
     */
    public void setChakanBaogao(String chakanBaogao) {
        this.chakanBaogao = chakanBaogao == null ? null : chakanBaogao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.chepaihao
     *
     * @return the value of surveyinfo.chepaihao
     *
     * @mbggenerated
     */
    public String getChepaihao() {
        return chepaihao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.chepaihao
     *
     * @param chepaihao the value for surveyinfo.chepaihao
     *
     * @mbggenerated
     */
    public void setChepaihao(String chepaihao) {
        this.chepaihao = chepaihao == null ? null : chepaihao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.VIN
     *
     * @return the value of surveyinfo.VIN
     *
     * @mbggenerated
     */
    public String getVin() {
        return vin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.VIN
     *
     * @param vin the value for surveyinfo.VIN
     *
     * @mbggenerated
     */
    public void setVin(String vin) {
        this.vin = vin == null ? null : vin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.dingsun_chexing
     *
     * @return the value of surveyinfo.dingsun_chexing
     *
     * @mbggenerated
     */
    public String getDingsunChexing() {
        return dingsunChexing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.dingsun_chexing
     *
     * @param dingsunChexing the value for surveyinfo.dingsun_chexing
     *
     * @mbggenerated
     */
    public void setDingsunChexing(String dingsunChexing) {
        this.dingsunChexing = dingsunChexing == null ? null : dingsunChexing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.chezhu_xingming
     *
     * @return the value of surveyinfo.chezhu_xingming
     *
     * @mbggenerated
     */
    public String getChezhuXingming() {
        return chezhuXingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.chezhu_xingming
     *
     * @param chezhuXingming the value for surveyinfo.chezhu_xingming
     *
     * @mbggenerated
     */
    public void setChezhuXingming(String chezhuXingming) {
        this.chezhuXingming = chezhuXingming == null ? null : chezhuXingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.zhengjian_leixing
     *
     * @return the value of surveyinfo.zhengjian_leixing
     *
     * @mbggenerated
     */
    public String getZhengjianLeixing() {
        return zhengjianLeixing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.zhengjian_leixing
     *
     * @param zhengjianLeixing the value for surveyinfo.zhengjian_leixing
     *
     * @mbggenerated
     */
    public void setZhengjianLeixing(String zhengjianLeixing) {
        this.zhengjianLeixing = zhengjianLeixing == null ? null : zhengjianLeixing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.chuxian_jiashiyuan
     *
     * @return the value of surveyinfo.chuxian_jiashiyuan
     *
     * @mbggenerated
     */
    public String getChuxianJiashiyuan() {
        return chuxianJiashiyuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.chuxian_jiashiyuan
     *
     * @param chuxianJiashiyuan the value for surveyinfo.chuxian_jiashiyuan
     *
     * @mbggenerated
     */
    public void setChuxianJiashiyuan(String chuxianJiashiyuan) {
        this.chuxianJiashiyuan = chuxianJiashiyuan == null ? null : chuxianJiashiyuan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.jiashizhenghao
     *
     * @return the value of surveyinfo.jiashizhenghao
     *
     * @mbggenerated
     */
    public String getJiashizhenghao() {
        return jiashizhenghao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.jiashizhenghao
     *
     * @param jiashizhenghao the value for surveyinfo.jiashizhenghao
     *
     * @mbggenerated
     */
    public void setJiashizhenghao(String jiashizhenghao) {
        this.jiashizhenghao = jiashizhenghao == null ? null : jiashizhenghao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.zhunjiachexing
     *
     * @return the value of surveyinfo.zhunjiachexing
     *
     * @mbggenerated
     */
    public String getZhunjiachexing() {
        return zhunjiachexing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.zhunjiachexing
     *
     * @param zhunjiachexing the value for surveyinfo.zhunjiachexing
     *
     * @mbggenerated
     */
    public void setZhunjiachexing(String zhunjiachexing) {
        this.zhunjiachexing = zhunjiachexing == null ? null : zhunjiachexing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.cheliangleibie
     *
     * @return the value of surveyinfo.cheliangleibie
     *
     * @mbggenerated
     */
    public String getCheliangleibie() {
        return cheliangleibie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.cheliangleibie
     *
     * @param cheliangleibie the value for surveyinfo.cheliangleibie
     *
     * @mbggenerated
     */
    public void setCheliangleibie(String cheliangleibie) {
        this.cheliangleibie = cheliangleibie == null ? null : cheliangleibie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.jiashiren_shifou_beibaoren
     *
     * @return the value of surveyinfo.jiashiren_shifou_beibaoren
     *
     * @mbggenerated
     */
    public String getJiashirenShifouBeibaoren() {
        return jiashirenShifouBeibaoren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.jiashiren_shifou_beibaoren
     *
     * @param jiashirenShifouBeibaoren the value for surveyinfo.jiashiren_shifou_beibaoren
     *
     * @mbggenerated
     */
    public void setJiashirenShifouBeibaoren(String jiashirenShifouBeibaoren) {
        this.jiashirenShifouBeibaoren = jiashirenShifouBeibaoren == null ? null : jiashirenShifouBeibaoren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.xingshizheng_zhuceriqi
     *
     * @return the value of surveyinfo.xingshizheng_zhuceriqi
     *
     * @mbggenerated
     */
    public Date getXingshizhengZhuceriqi() {
        return xingshizhengZhuceriqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.xingshizheng_zhuceriqi
     *
     * @param xingshizhengZhuceriqi the value for surveyinfo.xingshizheng_zhuceriqi
     *
     * @mbggenerated
     */
    public void setXingshizhengZhuceriqi(Date xingshizhengZhuceriqi) {
        this.xingshizhengZhuceriqi = xingshizhengZhuceriqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.xingshizheng_fazhengriqi
     *
     * @return the value of surveyinfo.xingshizheng_fazhengriqi
     *
     * @mbggenerated
     */
    public Date getXingshizhengFazhengriqi() {
        return xingshizhengFazhengriqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.xingshizheng_fazhengriqi
     *
     * @param xingshizhengFazhengriqi the value for surveyinfo.xingshizheng_fazhengriqi
     *
     * @mbggenerated
     */
    public void setXingshizhengFazhengriqi(Date xingshizhengFazhengriqi) {
        this.xingshizhengFazhengriqi = xingshizhengFazhengriqi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.shifou_baoan_chuxiandidian
     *
     * @return the value of surveyinfo.shifou_baoan_chuxiandidian
     *
     * @mbggenerated
     */
    public String getShifouBaoanChuxiandidian() {
        return shifouBaoanChuxiandidian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.shifou_baoan_chuxiandidian
     *
     * @param shifouBaoanChuxiandidian the value for surveyinfo.shifou_baoan_chuxiandidian
     *
     * @mbggenerated
     */
    public void setShifouBaoanChuxiandidian(String shifouBaoanChuxiandidian) {
        this.shifouBaoanChuxiandidian = shifouBaoanChuxiandidian == null ? null : shifouBaoanChuxiandidian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column surveyinfo.chuxiandidian
     *
     * @return the value of surveyinfo.chuxiandidian
     *
     * @mbggenerated
     */
    public String getChuxiandidian() {
        return chuxiandidian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column surveyinfo.chuxiandidian
     *
     * @param chuxiandidian the value for surveyinfo.chuxiandidian
     *
     * @mbggenerated
     */
    public void setChuxiandidian(String chuxiandidian) {
        this.chuxiandidian = chuxiandidian == null ? null : chuxiandidian.trim();
    }
}