package com.yanglin.dao;

import java.util.List;

import com.yanglin.model.HistorycaseInfo;

public interface HistorycaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historycaseinfo
     *
     * @mbggenerated
     */
    int insert(HistorycaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historycaseinfo
     *
     * @mbggenerated
     */
    int insertSelective(HistorycaseInfo record);

    List<HistorycaseInfo> getLishiPeianLiebiao(String baoDanHao);
}