package com.yanglin.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yanglin.model.Lossaccessment;

public interface LossaccessmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lossaccessment
     *
     * @mbggenerated
     */
    int insert(Lossaccessment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lossaccessment
     *
     * @mbggenerated
     */
    int insertSelective(Lossaccessment record);

    /**
     * 
     * @param claimNumber
     * @return
     */
    List<Lossaccessment> getLossInfoByClaimNumber(String claimNumber);

    
    Lossaccessment getLossInfoByClaimAndVehicleNumber(@Param("claimNumer1")String claimNumer, @Param("chepaihao1")String chepaihao);
}