package com.yanglin.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yanglin.model.LossaccessmentOpinions;

public interface LossaccessmentOpinionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lossaccessment_opinions
     *
     * @mbggenerated
     */
    int insert(LossaccessmentOpinions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lossaccessment_opinions
     *
     * @mbggenerated
     */
    int insertSelective(LossaccessmentOpinions record);

    /**
     * 
     * @param reportNo
     * @param chepaihao
     * @return
     */
    List<LossaccessmentOpinions> getLossOptionsByClaimAndVehicleNumber(@Param("reportNo")String reportNo, @Param("chepaihao")String chepaihao);
}