package com.yanglin.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yanglin.model.LossaccessmentLabors;

public interface LossaccessmentLaborsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lossaccessment_labors
     *
     * @mbggenerated
     */
    int insert(LossaccessmentLabors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lossaccessment_labors
     *
     * @mbggenerated
     */
    int insertSelective(LossaccessmentLabors record);

    /**
     * 
     * @param reportNo
     * @param chepaihao
     * @return
     */
    List<LossaccessmentLabors> getLossLaborByClaimAndVehicleNumber(@Param("reportNo")String reportNo, @Param("chepaihao")String chepaihao);
}