package com.yanglin.dao;

import org.apache.ibatis.annotations.Param;

import com.yanglin.model.LossaccessmentVehicle;

public interface LossaccessmentVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lossaccessment_vehicle
     *
     * @mbggenerated
     */
    int insert(LossaccessmentVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lossaccessment_vehicle
     *
     * @mbggenerated
     */
    int insertSelective(LossaccessmentVehicle record);

    LossaccessmentVehicle getVehicleInfoByClaimAndBrandNumber(@Param("baoanhao")String reportNo, @Param("chepaihao")String chepaihao);
}