package com.yanglin.dao;

import com.yanglin.model.LossaccessmentCasualites;

public interface LossaccessmentCasualitesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lossaccessment_casualites
     *
     * @mbggenerated
     */
    int insert(LossaccessmentCasualites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lossaccessment_casualites
     *
     * @mbggenerated
     */
    int insertSelective(LossaccessmentCasualites record);

    /**
     * 
     * @param reportNo
     * @return
     */
    LossaccessmentCasualites getLossaccessmentCasualitesByClaimnumber(String reportNo);
}