package com.yanglin.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yanglin.model.LossaccessmentSpareparts;

public interface LossaccessmentSparepartsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lossaccessment_spareparts
     *
     * @mbggenerated
     */
    int insert(LossaccessmentSpareparts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lossaccessment_spareparts
     *
     * @mbggenerated
     */
    int insertSelective(LossaccessmentSpareparts record);

    /**
     * 
     * @param reportNo
     * @param chepaihao
     * @return
     */
    List<LossaccessmentSpareparts> getSparepartsByClaimAndVehicleNumber(@Param("reportNo")String reportNo, @Param("chepaihao")String chepaihao);
}