package com.yanglin.dao;

import java.util.List;

import com.yanglin.model.PolicyRiskclass;

public interface PolicyRiskclassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_riskclass
     *
     * @mbggenerated
     */
    int insert(PolicyRiskclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table policy_riskclass
     *
     * @mbggenerated
     */
    int insertSelective(PolicyRiskclass record);

    List<PolicyRiskclass> getBaoxianXianbieInfo(String baoDanHao);
}