package com.yanglin.dao;

import java.util.List;

import com.yanglin.model.Reportinfo;

public interface ReportinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportinfo
     *
     * @mbggenerated
     */
    int insert(Reportinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reportinfo
     *
     * @mbggenerated
     */
    int insertSelective(Reportinfo record);
	
    /**
     * 
     * @param reportNo
     * @return
     */
    List<Reportinfo> getReportInfoByClaimNumber(String reportNo);

    
    List<String> getBaoDanListByClaimNumber(String reportNo);

    List<String> getDistinctReportNo();	
}