package com.yanglin.dao;

import org.apache.ibatis.annotations.Param;

import com.yanglin.model.SurveyInfo;

public interface SurveyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveyinfo
     *
     * @mbggenerated
     */
    int insert(SurveyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table surveyinfo
     *
     * @mbggenerated
     */
    int insertSelective(SurveyInfo record);

    
    SurveyInfo getSurveyInfoByClaimAndVehicleNumber(@Param("reportNo")String reportNo, @Param("chepaihao")String chepaihao);
    
    
}